phpstan/phpstan-doctrine

extension.neon
src/Type/Doctrine/EntityManagerMergeDynamicReturnTypeExtension.php
src/Type/Doctrine/ObjectManagerMergeDynamicReturnTypeExtension.php

Dynamically determine the return type of `EntityManager#merge`.
The merge function takes a single argument, the entity object  to re-attach with the EM. It passes back a managed copy of the entity, hence the return type is type of first argument.

Dynamic return type for EntityManager#merge

---

src/Type/Doctrine/EntityManagerGetRepositoryDynamicReturnTypeExtension.php

In our code we mostly typehint entity manager as `EntityManagerInterface` or even `ObjectManager` interface. This change should add support for them as well as for doctrine ODM's `DocumentManager`.

Add support for getRepository() call on ObjectManager interface

---

.travis.yml
composer.json
src/Reflection/Doctrine/DoctrineSelectableClassReflectionExtension.php
tests/PHPStan/Reflection/Doctrine/DoctrineSelectableClassReflectionExtensionTest.php
tests/PHPStan/Type/Doctrine/DoctrineSelectableDynamicReturnTypeExtensionTest.php
tests/PHPStan/Type/Doctrine/EntityManagerFindDynamicReturnTypeExtensionTest.php

Bumps requirements:
* php to ~7.1
* phpunit/phpunit to ^7.0
* phpstan/phpstan to ^0.10
* phpstan/phpstan-strict-rules to ^0.10
* phpstan/phpstan-phpunit to ^0.10

Compatibility with PHPStan 0.10

---

phpstan.neon
src/Type/Doctrine/EntityManagerFindDynamicReturnTypeExtension.php
tests/DoctrineIntegration/ORM/EntityManagerIntegrationTest.php
tests/DoctrineIntegration/ORM/data/entityManagerDynamicReturn.php
tests/DoctrineIntegration/ORM/data/entityManagerMergeReturn.php
tests/DoctrineIntegration/ORM/data/entityRepositoryDynamicReturn.php
tests/DoctrineIntegration/ORM/phpstan.neon

@ondrejmirtes there's also a small fix which I can move to another PR if needed.

Add integration tests for ORM features

---

extension.neon
src/Type/Doctrine/GetRepositoryDynamicReturnTypeExtension.php
src/Type/Doctrine/ManagerRegistryGetRepositoryDynamicReturnTypeExtension.php
src/Type/Doctrine/ObjectManagerGetRepositoryDynamicReturnTypeExtension.php
tests/DoctrineIntegration/Persistence/ManagerRegistryIntegrationTest.php
tests/DoctrineIntegration/Persistence/data/managerRegistryRepositoryDynamicReturn-2.json
tests/DoctrineIntegration/Persistence/data/managerRegistryRepositoryDynamicReturn.php
tests/DoctrineIntegration/Persistence/phpstan.neon

Similar to how ObjectManager:: getRepository works, but for ManagerRegistry

ManagerRegistry::getRepository returns correct EntityRepository

---

.travis.yml
composer.json
tests/DoctrineIntegration/ODM/DocumentManagerIntegrationTest.php
tests/DoctrineIntegration/ODM/data/documentManagerDynamicReturn.php
tests/DoctrineIntegration/ODM/data/documentManagerMergeReturn.php
tests/DoctrineIntegration/ODM/data/documentRepositoryDynamicReturn.php
tests/DoctrineIntegration/ODM/phpstan.neon

Same as #39 but without extra composer deps
Had to leave 'config.mongodb' in composer json so that it would allow installing doctrine-odm

Add integration tests for ODM features

---

README.md
extension.neon
src/Type/Doctrine/GetRepositoryDynamicReturnTypeExtension.php
src/Type/Doctrine/ObjectMetadataResolver.php
tests/DoctrineIntegration/ODM/DocumentManagerIntegrationTest.php
tests/DoctrineIntegration/ODM/data/customRepositoryUsage-2.json
tests/DoctrineIntegration/ODM/data/customRepositoryUsage.php
tests/DoctrineIntegration/ODM/document-manager.php
tests/DoctrineIntegration/ODM/phpstan.neon
tests/DoctrineIntegration/ORM/EntityManagerIntegrationTest.php
tests/DoctrineIntegration/ORM/data/customRepositoryUsage-2.json
tests/DoctrineIntegration/ORM/data/customRepositoryUsage.php
tests/DoctrineIntegration/ORM/entity-manager.php
tests/DoctrineIntegration/ORM/phpstan.neon

#40, rebased on #48
as in the original, with this implementation we're able to use the class metadata to retrieve repository information, given the user provides the entity/document manager instance.
Additionally, will use default `repositoryClass` when no `objectManagerLoader` is provided.

Use real object managers

---

src/Rules/Doctrine/ORM/MagicRepositoryMethodCallRule.php
tests/Rules/Doctrine/ORM/MagicRepositoryMethodCallRuleTest.php
tests/Rules/Doctrine/ORM/data/MySecondEntity.php
tests/Rules/Doctrine/ORM/data/dql.php
tests/Rules/Doctrine/ORM/data/magic-repository.php

Do not generate an error if a custom findByX (or findOneByX, countByX) method exists but X is not a field in the entity class.
This should fix #52

Do not error if a non-field findByX method exists

---

tests/DoctrineIntegration/ODM/DocumentManagerIntegrationTest.php
tests/DoctrineIntegration/ORM/EntityManagerIntegrationTest.php
tests/DoctrineIntegration/Persistence/ManagerRegistryIntegrationTest.php

another attempt to fix 7cc0e00fa5961f609fe04643b74f951df0a1c1f9 and  73c8ebd86343fbfa4cc0477f798909f430332ac4
Ref https://github.com/phpstan/phpstan-doctrine/pull/81

Tests: use PHPStan binary directly

---

README.md

Otherwise there is a deprecation reported: Service '0': option 'class' should be changed to 'factory'

README: ReflectionDescriptor should use 'factory' instead of 'class'

---

src/Type/Doctrine/GetRepositoryDynamicReturnTypeExtension.php
tests/DoctrineIntegration/ORM/data/entityManagerDynamicReturn-2.json
tests/DoctrineIntegration/ORM/data/entityManagerDynamicReturn-7.json
tests/DoctrineIntegration/ORM/data/entityManagerDynamicReturn.php

Previously this bug hasn't been detected:
```php
/**
* @param class-string $entityName
*/
public function doSomethingWithEntity(string $entityName): void
{
$repository = $this->entityManager->getRepository($entityName);
$repository->createQueryBuilder('a')->unknownMethod(); // bug
```

GetRepositoryDynamicReturnTypeExtension: improved return type when argument is not recognized

---

stubs/ClassMetadataInfo.stub

This will fix false positives when using the returned string from `ClassMetadaInfo::getAssociationTargetClass` as `class-string` param
Example code:
```php
final class SelectInLoader
{
/** @var EntityManagerInterface */
private $em;
public function __construct(EntityManagerInterface $em)
{
$this->em = $em;
}
/**
* @return Address[]
*/
public function overlyComplicatedWayToGetCustomerAddresses(Customer $customer): array
{
$addressClass = $this->em
->getClassMetadata(Customer::class)
->getAssociationTargetClass('address');
return $this->em->getRepository($addressClass)->findBy(['customer' => $customer]);
}
}
```
Current (false positive) phpstan errors:
```
------ ------------------------------------------------------------- 
Line   SelectInLoader.php …
```

Add ClassMetadataInfo::getAssociationTargetClass stub

---

rules.neon
src/Rules/Doctrine/ORM/EntityNotFinalRule.php
tests/Rules/Doctrine/ORM/EntityNotFinalRuleTest.php
tests/Rules/Doctrine/ORM/data/FinalEntity.php
tests/Rules/Doctrine/ORM/data/FinalNonEntity.php

I create all my classes as final by default. This however can cause issues with Doctrine:
```
[Doctrine\Common\Proxy\Exception\InvalidArgumentException]
Unable to create a proxy for a final class "<entity class>".
```
What do you think about a rule to avoid final entities?

Check that doctrine entities are not final

---

src/Type/Doctrine/QueryBuilder/QueryBuilderMethodDynamicReturnTypeExtension.php
src/Type/Doctrine/QueryBuilder/QueryBuilderTypeSpecifyingExtension.php
tests/DoctrineIntegration/ORM/data/queryBuilder.php

Since version 0.12.18 I have a weird error:
```
QueryBuilder: [Syntax Error] line 0, col -1: Error: Expected IdentificationVariable | ScalarExpression | AggregateExpression | FunctionDeclaration | PartialObjectExpression | "(" Subselect ")" | CaseExpression, got end of string.
DQL: SELECT
```
It is reported in code that uses the `QueryBuilder::setParameters()` method. I first replaced those calls with several `QueryBuilder::setParameter()` calls and the errors were not reported anymore, but it was an unsatisfactory solution.
I noticed that in that version, a new stub was added for the `QueryBuilder::setParameters()` method so I tried editing it. When replacing `@return static` with `@return self`, the errors were not reported anymore. I have no idea why this fixes the issue though so …

Fix empty DQL with QueryBuilder::setParameters()

---

README.md

In Symfony 5, the recipe does not create a `config/bootstrap.php` file. 
It should be located in `tests` folder if you have some tests, or missing if not, so I added a link to document how to deal with that file.

Add documentation on bootstrap file with Symfony 5+

---

composer.json
extension.neon
src/Type/Doctrine/Collection/FirstTypeSpecifyingExtension.php
tests/Type/Doctrine/Collection/FirstTypeSpecifyingExtensionTest.php
tests/Type/Doctrine/Collection/VariableTypeReportingRule.php
tests/Type/Doctrine/Collection/data/collection.php

I really wanted support for `Collection::isEmpty()` together with `Collection::first()` as proposed in https://github.com/phpstan/phpstan-doctrine/pull/153.
This adds tests and they pass.
However, I'm not too sure if the logic in the extension is correct. 
When I change the code to:
```php
$classReflection = $methodReflection->getDeclaringClass();
$methodVariants = $classReflection->getNativeMethod(self::FIRST_METHOD_NAME)->getVariants();
if ($context->truthy()) {
return $this->typeSpecifier->create(
new MethodCall($node->var, self::FIRST_METHOD_NAME),
new ConstantBooleanType(false),
$context
);
}
return $this->typeSpecifier->create(
new MethodCall($node->var, self::FIRST_METHOD_NAME),
TypeCombinator::remove(ParametersAcceptorSelector::selectSingle($methodVariants)->getReturnType(), new …
```

Narrow type of Collection::first() when using Collection::isEmpty()

---

extension.neon
src/Type/Doctrine/Collection/IsEmptyTypeSpecifyingExtension.php
tests/Type/Doctrine/Collection/IsEmptyTypeSpecifyingExtensionTest.php
tests/Type/Doctrine/Collection/data/collection.php

Now that we have #172 , we should do the same for `last()`.

Narrow type of Collection::last() when using Collection::isEmpty()

---

README.md

The code is taken from https://github.com/phpstan/phpstan-symfony/issues/141#issuecomment-817485623
Question:
> ... allows DQL validation when enabled
How can you enable this?

Adding object-manager.php for Symfony 5

---

src/Rules/Doctrine/ORM/EntityColumnRule.php
tests/Rules/Doctrine/ORM/EntityColumnRuleTest.php
tests/Rules/Doctrine/ORM/data/CustomNumericType.php
tests/Rules/Doctrine/ORM/data/EntityWithCustomType.php
tests/Rules/Doctrine/ORM/data/MyBrokenEntity.php

See https://github.com/phpstan/phpstan-doctrine/issues/187#issuecomment-842256098
Hopefully I did it right. 
This makes sure the mismatch error is more clear.

Report correct type on type mapping mismatch

---

src/Rules/Doctrine/ORM/EntityNotFinalRule.php
tests/Rules/Doctrine/ORM/EntityNotFinalRuleTest.php
tests/Rules/Doctrine/ORM/data/FinalAnnotatedEntity.php

I just update the plugin from `0.12.33` to `0.12.34` and after this i got several messages about making my entities not final because of how doctrine works, which is right. But my entities are not final on language level. I would expect that this message is not displayed if i annotate the entity to be final. So i added a testcase based on my expected behavior. If it is working right now as expected i would change the test accordingly :)
Why does this happen now? I dont know, i looked into the diff between the two releases and did not find which changes caused this. This feature is bleeding edge since `0.12.20` it should have happened before i guess.
PS: i did not run the testcase locally wanted the workflow to do the work 😆

Add testcase for entities that are annotated final

---

stubs/EntityManager.stub
stubs/EntityManagerInterface.stub

Updating stubs to add new deprecations.
This is a fix related to this issue: https://github.com/phpstan/phpstan-deprecation-rules/issues/40, because of the stubs the errors were not being shown.

(fix): copy and merge are deprecated

---

composer.json
extension.neon
tests/Rules/Doctrine/ORM/EntityColumnRuleTest.php
tests/Rules/Doctrine/ORM/data/MyBrokenEntity.php

This PR adds type descriptors for [Carbon](https://carbon.nesbot.com/) date types Carbon and CarbonImmutable using the ReflectionDescriptor.
Made possible after: https://github.com/briannesbitt/Carbon/pull/2344.

Carbon Type Descriptors via ReflectionDescriptor

---

src/Type/Doctrine/ObjectMetadataResolver.php

Clearly indicate if the file exists or is not readable, also mention the file path.
See #233

Use explicit errors for invalid object manager loader file

---

src/Type/Doctrine/Query/QueryResultDynamicReturnTypeExtension.php
tests/Type/Doctrine/data/QueryResult/queryBuilderGetQuery.php
tests/Type/Doctrine/data/QueryResult/queryResult.php

Fixes #259 
Normally we assume the type of `Query<ResultType>::getResult()` to be `array<ResultType>`. However, we also assume that `Query<void>::getResult()` returns a `int` (`void` denotes an INSERT or DELETE query).
So we can not assume the type of `Query<ResultType>::getResult()` to be `array<ResultType>` if there is a chance that `ResultType` is `void`.
In this PR I change the `DynamicReturnTypeExtension` of Query::getResult() so that no return type is assumed when ResultType may be void.
Note:
This has an impact on this feature when used in conjunction with template types, as this is not valid anymore:
```
/**
* @template T
* @param Query<T> $q
* @return array<T>
*/
function test($q) {
return $q->getResult(); // mixed
}
```
However, this is valid:
```
/**
* @template T of …
```

We can not assume the type of Query::getResult() if ResultType may be void

---

src/Type/Doctrine/Query/QueryResultTypeWalker.php
tests/Type/Doctrine/Query/QueryResultTypeWalkerTest.php
tests/Type/Doctrine/data/QueryResult/Entities/CompoundPk.php
tests/Type/Doctrine/data/QueryResult/Entities/CompoundPkAssoc.php
tests/Type/Doctrine/data/QueryResult/Entities/Many.php

Supports `IDENTITY(a.assoc)` or `IDENTITY(a.assoc, 'id_field')` where `id_field` is the name of one of the id fields of the target class.
Does not support `IDENTITY(a.assoc)` when the target id field is also an association (this is inferred to mixed).

Add IDENTITY() type inference support

---

README.md

Hi @ondrejmirtes 
Some days ago, the `allowNullablePropertyForRequiredField` setting was added https://github.com/phpstan/phpstan-doctrine/pull/208 but there is currently no mention about it in the readme. I think something should be added.
I don't know if you just want a mention like I did or something more explicit or a whole readme section about it.

Add allowNullablePropertyForRequiredField mention into the Readme

---

extension.neon
phpstan.neon
src/Type/Doctrine/QueryBuilder/OtherMethodQueryBuilderParser.php
src/Type/Doctrine/QueryBuilder/QueryBuilderGetQueryDynamicReturnTypeExtension.php
src/Type/Doctrine/QueryBuilder/QueryBuilderMethodDynamicReturnTypeExtension.php
tests/Type/Doctrine/data/QueryResult/queryBuilderGetQuery.php

Closes #266 
Uses `searchOtherMethodsForQueryBuilderBeginning` also in `QueryBuilderGetQueryDynamicReturnTypeExtension`.

Determine queryBuilderType if getQuery is called immediately
